version: "3"

services:

  postgres:
    image: postgres:14.7
    restart: always
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    image: bitnami/clickhouse:latest
    volumes:
      - clickhouse-data:/bitnami/clickhouse
    environment:
      - CLICKHOUSE_ADMIN_USER=clickhouse
      - CLICKHOUSE_ADMIN_PASSWORD=clickhouse
    ports:
      - "8123:8123"

volumes:
  postgres-data:
    name: "Postgres_data"
  clickhouse-data:
    name: "ClickHouse_data"
